name: ergosanitas backend laravel 11

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

concurrency:
  # Define un grupo de concurrencia basado en la referencia de la rama
  group: ci-${{ github.ref }}
  # Cancela cualquier ejecución anterior en progreso para esta rama
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Laravel 11 requiere PHP 8.2
          tools: composer

      - name: Instalar dependencias de Laravel
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Subir `.env` al servidor
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Configurar permisos de Laravel
        run: |
          chmod -R 775 storage bootstrap/cache
          chmod -R 775 public

      - name: Deshabilitar needrestart temporalmente
        run: sudo sh -c 'echo "I0" > /etc/needrestart/conf.d/no-restart.conf'

      - name: Crear carpetas necesarias en HostGator con FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          set ftp:ssl-allow no
          set net:max-retries 5
          set net:timeout 60
          set mirror:parallel-transfer-count 5
          set ftp:passive-mode on
          mkdir -p /public_html/laravel_app/
          mkdir -p /public_html/laravel_app/bootstrap/cache
          mkdir -p /public_html/laravel_app/storage/framework/{sessions,views,cache}
          mirror -R --only-newer . /public_html/laravel_app/
          quit
          EOF

      - name: Ajustar permisos en HostGator
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          chmod -R 775 /public_html/laravel_app/storage
          chmod -R 775 /public_html/laravel_app/bootstrap/cache
          quit
          EOF


#      - name: Ejecutar migraciones en HostGator (opcional)
#        run: php artisan migrate --force
