name: ergosanitas backend laravel 11

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Laravel 11 requiere PHP 8.2
          tools: composer

      - name: Instalar dependencias de Laravel
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Subir `.env` al servidor
        run: |
          if [ -z "${{ secrets.LARAVEL_ENV }}" ]; then
            echo "ERROR: No se encontró LARAVEL_ENV en los secrets" >&2
            exit 1
          fi
          echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Configurar permisos de Laravel
        run: chmod -R 775 storage bootstrap/cache

      - name: Instalar lftp
        run: sudo NEEDRESTART_MODE=a apt-get install -y lftp

      - name: Crear carpetas necesarias en HostGator con FTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          set ftp:ssl-allow no
          set net:max-retries 5
          set net:timeout 60
          set ftp:passive-mode on

          cls /public_html/laravel_app/ || mkdir /public_html/laravel_app/
          cls /public_html/laravel_app/bootstrap/cache || mkdir /public_html/laravel_app/bootstrap/cache
          cls /public_html/laravel_app/storage/framework/sessions || mkdir /public_html/laravel_app/storage/framework/sessions
          cls /public_html/laravel_app/storage/framework/views || mkdir /public_html/laravel_app/storage/framework/views
          cls /public_html/laravel_app/storage/framework/cache || mkdir /public_html/laravel_app/storage/framework/cache

          mirror -R --only-newer . /public_html/laravel_app/
          quit
          EOF

      - name: Ajustar permisos en HostGator
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          chmod -R 775 /public_html/laravel_app/storage
          chmod -R 775 /public_html/laravel_app/bootstrap/cache
          quit
          EOF

#      - name: Ejecutar migraciones en HostGator (opcional)
#        run: php artisan migrate --force
