name: Ergosanitas CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para producción

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configurar PHP y Composer para Laravel
      - name: Configurar PHP y Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Instalar dependencias de Laravel
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Configurar archivo `.env`
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Ejecutar migraciones
        run: php artisan migrate --force

      - name: Limpiar y cachear configuración
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Otorgar permisos a storage y bootstrap
        run: chmod -R 777 storage bootstrap/cache

      # Instalar `lftp` de forma segura
      - name: Instalar lftp
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y lftp

      # Subir archivos al servidor con FTP
      - name: Subir archivos con lftp
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp.ergosanitas.com <<EOF
          set ftp:ssl-allow no
          set net:max-retries 5
          set net:timeout 60
          set mirror:parallel-transfer-count 1
          set ftp:passive-mode on
          mkdir -p /public_html/laravel_app/
          mirror -R . /public_html/laravel_app/
          quit
          EOF
